Nemo2011/bilibili-api

.github/CONTRIBUTING.md
bilibili_api/live.py

- 1. live.LiveDanmaku.logger
- 2. 一点文档笔误？

fix: 修复连接直播间时重复添加 handler 导致重复输出的错误

---

bilibili_api/data/api/session.json
bilibili_api/data/api/user.json
bilibili_api/session.py
bilibili_api/user.py
docs/examples/session.md
docs/modules/session.md
docs/modules/user.md
requirements.txt

把消息会话相关写在了 **session.py** 模块里
- 新增了相关接口 **session.json** 。
- 将 **user.send_msg** 相关函数、接口与文档转移至 **session** 对应位置。
- 通过轮询实现了 **Session** 类，可以接收消息并使用类似 **live.LiveDanmaku.on()** 方式派发任务。
- 经测试私聊可以正常使用，但后续可能还有应援团相关bug。
- 代码、文档规范这块我可能做的不是很好，还请斧正。

单独把消息（私信、应援团等）做了一个模块

---

bilibili_api/bangumi.py
bilibili_api/data/api/bangumi.json
docs/modules/bangumi.md
tests/test_bangumi.py

Bangumi 模块对特殊番剧的基本信息获取适配，兼容原来的方法
```
bilibili_api/bangumi.py
bilibili_api/data/api/bangumi.json
tests/test_bangumi.py
docs/modules/bangumi.md
```
可以获取港澳台番剧相关信息
-  重构了 `Bangumi` 的 `init` 类方法，采用构造参数的方式，去除重复if else.
-  适配了 `get_episode_list`，尽力将不同转换为同一字段
-   兼容了其他 `Bangumi`类的方法（更改了以 season_id为请求参数的方法）
-  增加了`oversea` 参数
-  增加了对于港澳番剧基础信息的 Api 索引
- 增加了 `get_up_info` 方法，获取番剧是出差还是大陆
- 增加了 `get_raw` 方法，获取初始化得到的，和 `get_overview` 一个格式的数据
-  增加了 `Bangumi `参数 `epid` 可以根据剧集id获取对应番剧信息和剧集列表
-  增加了 `get_episode_info` 方法(内含抛出错误的else)，和 `Episode` 类里那个功能一样
-  增加了测试例在 `tests/test_bangumi.py` 中
#57

Bangumi 模块对特殊番剧的基本信息获取适配，兼容原来的方法

---

bilibili_api/data/api/user.json
bilibili_api/data/api/video.json
bilibili_api/user.py
docs/modules/user.md
tests/test_user.py

| 参数      | type                | description                     |
|-----------|---------------------|---------------------------------|
| page_num  | int, optional       | 页码，从 1 开始. Defaults to 1.       |
| page_size | int, optional       | 每一页的相簿. Defaults to 30.         |
| biz       | AlbumType, optional | 排序方式. Defaults to AlbumType.ALL |
+ album
+ space_notice
+ set_space_notice
+ user_tag(ajax)
获取用户投稿相簿。
http://space.bilibili.com/ajax/tags/getSubList
目前不可用，因为 ajax 重定向没有被 预定的工具库处理，另外处理后也因为没有code字段不能被解析。

[Enhancement] 增加相簿的获取方法，主页公告的获取,设置方法(User模块) 

---

bilibili_api/bangumi.py
bilibili_api/data/api/user.json
bilibili_api/user.py
docs/modules/user.md
tests/test_user.py

```
获取用户关注的 Tag 信息，如果用户设为隐私，则返回 获取登录数据失败
Returns:
dict: 调用接口返回的内容。
```
预览
```yaml
{'status': False, 'data': '获取登录数据失败'}
```
`get_user_fav_tag` 的逻辑在此次 Pr 中没有打包到至 utils
#66 Issue

[Enhancement] 增加用户关注Tag的获取方法

---

bilibili_api/data/api/live.json
bilibili_api/data/api/user.json
bilibili_api/live.py
bilibili_api/user.py
docs/modules/live.md
docs/modules/user.md
tests/test_user.py

```
读取用户粉丝牌详细列表，如果隐私则不可以
Returns:
dict: 调用接口返回的内容。
```
```
Args:
roomId(int, optional): 指定房间，查询是否拥有此房间的粉丝牌
target_id(int, optional): 指定返回一个主播的粉丝牌，留空就不返回
page_num(int, optional): 粉丝牌列表，默认 1
```
获取用户拥有的粉丝牌列表
接口对应为 主页，直播间
+ 增加文档
+ 增加部分例子
**此改动需要额外测试**
+ 增加 Api 数据

[Enhancement] 增加 直播类&用户类 的 拥有的粉丝勋章列表获取方法 (Web Api)

---

bilibili_api/utils/short.py

`get_real_url` failed to parse video share shortlink correctly. The stack trace is attached below.
```
>>> B.sync(B.get_real_url("https://b23.tv/JiaCLnr"))
https://b23.tv/JiaCLnr
https://www.bilibili.com/video/BV1QB4y1J78L?is_story_h5=false&p=1&share_from=ugc&share_medium=android&share_plat=android&share_session_id=17da308a-057c-4f77-949a-abfd18648354&share_source=COPY&share_tag=s_i&timestamp=1664246722&unique_k=JiaCLnr
/video/BV1QB4y1J78L/?is_story_h5=false&p=1&share_from=ugc&share_medium=android&share_plat=android&share_session_id=17da308a-057c-4f77-949a-abfd18648354&share_source=COPY&share_tag=s_i&timestamp=1664246722&unique_k=JiaCLnr
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/kun/.local/lib/python3.10/site-packages/bilibili_api/utils/sync.py", …
```

fix: 修正了短链接解析未按预期工作的问题

---

bilibili_api/login.py

login.py 467行 验证码登录 login_with_sms 报错 KeyError
`return_data["status"]` 已改为 `return_data["data"]["status"]`
Response `{'code': 0, 'message': '0', 'ttl': 1, 'data': {'is_new': False, 'status': 0, 'message': '', 'url': '', 'hint': '登录成功', 'in_reg_audit': 0, 'refresh_token': '', 'timestamp': }}`

login_with_sms update

---

bilibili_api/search.py

`bilibili_api/search.py` 中 `search_by_type()` 方法，当搜索10分钟以下时长视频时，接口参数的正确duration值应为1。（如图所示
盲猜应该是写代码时复制的上一行，不小心没改过来~(dog
- 1. {修复} search_by_type接口duration参数值的错误

search_by_type接口搜索10分钟以下时长视频duration值应为1

---

bilibili_api/data/api/session.json
bilibili_api/session.py
bilibili_api/utils/Picture.py
docs/examples/session.md
docs/modules/session.md

现在 ```session.py``` 已经适配新 ```Picture``` 类 (#130)
实现了发送图片消息，因此原先参数 ```text``` 已更名为更合适的 ```content```。
同时 ```send_msg()``` 新增必要参数 ```msg_type``` 用于区分要发送消息的类型。
新增了一个 ```Picture``` 类的上传函数 ```upload_file()``` 具体描述见 commit。

session.py 适配新 Picture 类

---

bilibili_api/utils/AsyncEvent.py

函数下的注释明明就是”*args, **kwargs:  要传递给函数的参数。“，那为什么函数还是单个参数呢？

fix: 修改事件发布时单个参数为可变参数

---

.github/workflows/python-publish.yml
.github/workflows/testing.yml

修复 github action 警告：在 `actions/setup-python@v3` 版本使用了即将被弃用的命令 `set-output`

fix: github action warning

---

bilibili_api/video_uploader.py

- 1. {新增} None
- 2. {修复} fixed upload video chunk timeout issue and upload cover image key issue
I think some of the cdn server are not reliable. preupload has a list of endpoints, so I added a random choice to try all endpoints at each retry.
timeout, issue
```
{'name': 'PREUPLOAD', 'data': ({<bilibili_api.video_uploader.VideoUploaderPage object at 0x7f01935f8760>: <bilibili_api.video_uploader.VideoUploaderPage object at 0x7f01935f8760>},)}
{'name': 'PRE_PAGE', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x7f01935f8760>},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x7f01935f8760>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 3},)}
{'name': 'PRE_CHUNK', 'data': ({'page': …
```

Fix upload chunk timeout issue and upload cover image url key issue

---

bilibili_api/data/api/video_tag.json
bilibili_api/video_tag.py
docs/examples/video_tag.md
tests/test_video_tag.py

get_card() 只能获取最顶部的几个视频，后面的一些视频就不能获取了。
通过https://api.vc.bilibili.com/topic_svr/v1/topic_svr/topic_history，传入offset_dynamic_id，可以依此方法获取指定dynamic_id的视频后开始的视频。

获取指定tag下的后面的视频/动态

---

bilibili_api/user.py
bilibili_api/utils/network_httpx.py

- 还有 mixin_key 可能出现的下标越界
- wts也要参与计算
- user.get_user_info() 函数参数修正
是不是所有函数参数都要重写啊晕了

fix: 修复 w_rid 计算漏洞

---

bilibili_api/ass.py
bilibili_api/exceptions/CredentialNoAcTimeValue.py
bilibili_api/exceptions/CredentialNoBiliJctException.py
bilibili_api/exceptions/CredentialNoBuvid3Exception.py
bilibili_api/exceptions/CredentialNoDedeUserIDException.py
bilibili_api/exceptions/CredentialNoSessdataException.py
bilibili_api/utils/credential.py

**BREAKING CHANGE**
将 `ass.make_ass_file_subtitle` 中 `name` 改为 `lan_name`
强行要求提供 `credential`（实在是没看到哪个不需要凭据
将 `credential.has_sessdata` 判定标准增加空字符串

credential 处理空字符串以及 ass 提供 credential

---

bilibili_api/live.py

`直播弹幕获取不到（除了头两次连接后），对比blivedm源码，发现ws_connect增加header可以解决。怀疑服务器加了简单过滤。
- 2. {修复}

debug 直播弹幕获取不到

---

.github/workflows/python-publish.yml
setup.py

- 需要在 `dev` 分支发布 `release`
- 现在会自动把发布 `release` 时的 `tag` 作为 `setup.py` 中的 `version`
- `tag` 推荐使用 PyPI 的版本规则 [PEP 440](https://peps.python.org/pep-0440/#pre-releases) 形如 `X.Y.ZbN` 例 `16.0.1b1`
- 但是也可以使用 [语义化版本](https://semver.org/lang/zh-CN/) 中的规则 `16.0.1-beta.1`，会被自动转换成上版本号

feat: bilibili-api-dev 库自动发布

---

bilibili_api/ass.py

- 1. {新增}
- 2. {修复}
修复获取弹幕时发生的异常
- 3. {其他}
在 https://github.com/Nemo2011/bilibili-api/commit/f6ec0aa573a922d7d69619739606651d93b69769 提交中将 `__get_page_id_by_index` 更名为了 `__get_cid_by_index`，IDE 会自动对所有引用进行重命名，但由于此处在类外调用隐藏方法用了[名称改写](https://www.geeksforgeeks.org/name-mangling-in-python/)，导致 IDE 没有识别到，进而引发了函数不存在的异常。

fix: 修复获取弹幕时发生的异常

---

bilibili_api/data/api/user.json
bilibili_api/user.py
docs/modules/user.md
tests/test_user.py

接口：https://api.bilibili.com/x/v2/medialist/resource/list
新增 MedialistOrder， get_media_list()
同时更新API, docs, test
部分参数（mobi_app， type，oid，otype，direction，with_current）的作用仍未知
经测试[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1X6HIAI3W22AjWHI1v_EMrfFTzjAGTwUg?usp=sharing)可以获得期望的结果
注意到：
分P视频被视为一个视频
合集被展开为多个视频

Implement get_media_list() in User

---

bilibili_api/article.py
bilibili_api/dynamic.py
bilibili_api/login.py
bilibili_api/note.py
bilibili_api/settings.py
bilibili_api/user.py
bilibili_api/utils/network.py
bilibili_api/utils/parse_link.py
bilibili_api/utils/utils.py
bilibili_api/video.py
bilibili_api/video_tag.py
bilibili_api/vote.py
bilibili_api/watchroom.py
tests/test_login.py

- 1. 新增同步请求
- 2. 修复二维码登录异常
- 3. 修改get_api可传入多个参数取值

feat: 新增同步请求, 替换部分httpx代码处

---

pyproject.toml

- 1. {新增}
- 2. {修复}
之前的写法实测会导致安装依赖时仅安装 bilibili_api 文件夹内的文件，所有的子目录（如 utils、errors）均被忽略。
该 PR 摘抄了原有 setup.py 文件中关于 package 和 package-data 的描述，测试正常工作。
- 3. {其他}

fix: 修复安装时文件缺失的错误

---

bilibili_api/video.py

当获取历史弹幕时`danmakus = await v.get_danmakus(0, date=danmaku_date)` 
，需要初始化from_seg，to_seg。
否则下面语句 `for seg in range(from_seg, to_seg+1)`
会产生TypeError。

fix TypeError: 'NoneType' + 'int' in history danmuku

---

bilibili_api/utils/parse_link.py

为`parse_link`添加了处理拜年纪url中没有bvid的情况，通过Nemo说的`__INITIAL_STATE__`来获取bvid
- 目前返回所有返回值里第一个视频（也就是正片第一个）
如果认为返回整个`dict`或者返回一个全部`bvid`的列表，我也可以改一下。（词典会稍稍麻烦些因为没法塞到Video类里，然后列表的话就看不到分类（比如说正片，单品，等等））

feat: add bnj to be able to resolve url without bvid in `parse_link` by __INITIAL_STATE__

---

bilibili_api/session.py
docs/examples/session.md
docs/modules/session.md

- 重载装饰器
- 重命名启动函数参数 `except_self` 为 `exclude_self`
- 一些注释修改
- 现在使用 `logging.error` 打印错误提示

fix session

---

bilibili_api/utils/aid_bvid_transformer.py

BV 号 av 号转换算法不适用于 av 号大于 29460791296 的情况
最近获取不到下载链接了，发现bvid都转换不了
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/misc/bvid_desc.md
https://github.com/SocialSisterYi/bilibili-API-collect/issues/740
- 1. {新增}
- 2. {修复}
- 3. {其他}

fix: bvid2aid

---

bilibili_api/utils/sync.py

- 1. {新增}修改sync的逻辑以支持在事件循环已经运行时同步执行异步代码
- 2. {修复}
- 3. {其他}

支持在事件循环已经运行时同步执行异步代码

---

bilibili_api/comment.py

The real default page size of this API is 20, but we should follow the old behaviour.
- 1. 新增：允许为 get_sub_comments 设置 page_size

feat: allow to edit page_size of sub_comments

---

bilibili_api/video.py

Bilibili 的弹幕接口请求 `comment.bilibili.com` 现需要 `User-Agent` 头部，否则会引发风控。
测试：
- 无 `User-Agent` 头部：
```
$ python -c 'import requests; print(requests.get("https://comment.bilibili.com/279786.xml"))'
<Response [412]>
```
- 有 `User-Agent` 头部：
```
$ python -c 'import requests; print(requests.get("https://comment.bilibili.com/279786.xml", headers={"User-Agent":"Mozilla/5.0"}))'
<Response [200]>
```
此 Pull Request 为 `get_danmaku_xml` 中的请求添加了 `User-Agent: Mozilla/5.0` 的头部，其功能恢复正常。

fix: get_danmaku_xml 发起的请求现需要 `User-Agent` 头部

---

bilibili_api/user.py
bilibili_api/utils/user_render_data.py
requirements.txt

获取用户个人页面静态渲染数据工具 用于获取 user 部分接口风控所需的  "w_webid" 参数内容 由于跟用户相关 所以在User类型新增属性 __access_id  防止同一 User 对象重复获取  在对象自身懒加载存储 采用解析 JWT 的方式判断是否有效 
- 1. {新增}  在utils下新增解析用户个人页静态渲染数据工具 
- 2. {修复} User.get_user_info, User.get_live_info 接口风控校验失败
- 3. {其他} 引入新的依赖 PyJWT 用于解析 access_id 对应的 JWT 是否有效

修复用户部分接口风控校验失败

---

bilibili_api/data/api/live.json
bilibili_api/live.py
docs/modules/live.md
tests/test_live.py

直播禁言用户添加hour参数
近期禁言用户api新增hour参数，缺少此参数会导致禁言失败又不报错。
给ban_user新增hour参数，并相应修改了api，测试，与文档

直播禁言用户添加hour参数

---

bilibili_api/search.py
bilibili_api/utils/utils.py
docs/modules/search.md

本次 Pull Request 主要完成了以下更改：
1. **新增功能：**
- **`search.search_by_type` 新增参数：**
- `time_start` 和 `time_end` 用于支持按照时间段进行查询。
- 时间段参数的使用方式：
- `time_start`：查询的起始时间，格式为 `YYYY-MM-DD`。
- `time_end`：查询的结束时间，格式为 `YYYY-MM-DD`。
- 功能特点：支持精准的时间段过滤。
- **新增工具函数 `to_timestamps`：**
- 文件位置：`utils.utils`
- 功能描述：将日期字符串（如 `YYYY-MM-DD`）转换为 Unix 时间戳。
- 参数说明：
- `date_str` (str): 日期字符串，格式为 `YYYY-MM-DD`。
- 返回值：对应的 Unix 时间戳（整数）。
- 用途：辅助时间段查询功能，确保输入的时间参数能够被正确解析。

search.search_by_type 增加功能：可以按照时间段查询 & 新增 to_timestamps 函数

---

bilibili_api/data/api/user.json

当前视频合集API地址解析后为：
https://api.bilibili.com/x/polymer/space/seasons_archives_list?mid=391930545&season_id=598034&sort_reverse=false&page_num=1&page_size=100&wts=1737513661&web_location=1550101&w_rid=42092757abce9f53520da3ca3a308192
返回404
新API地址为：
https://api.bilibili.com/x/polymer/web-space/seasons_archives_list?mid=391930545&season_id=598034&sort_reverse=false&page_num=1&page_size=100&wts=1737513661&web_location=1550101&w_rid=42092757abce9f53520da3ca3a308192

fix: 查看用户合集中的视频（新版）API变更

---

bilibili_api/session.py

修复 get_at api 输入参数命名错误 last_uid -> last_uid
为保证兼容性同样保留了原始参数

[fix]修复 get_at 输入参数命名错误

---

bilibili_api/user.py
bilibili_api/utils/user_render_data.py

在云服务器 IP 请求用户视频时，遇到 412 错误
```python
----> 1 await u.get_videos()
File ~/.local/lib/python3.13/site-packages/bilibili_api/user.py:463, in User.get_videos(self, tid, pn, ps, keyword, order)
436 """
437 获取用户投稿视频信息。
438 
(...)    451     dict: 调用接口返回的内容。
452 """
453 api = API["info"]["video"]
454 params = {
455     "mid": self.__uid,
456     "ps": ps,
457     "tid": tid,
458     "pn": pn,
459     "keyword": keyword,
460     "order": order.value,
461     "order_avoided": True,
462     "platform": "web",
--> 463     "w_webid": await self.get_access_id(),
464 }
465 return (
466     await Api(**api, credential=self.credential).update_params(**params).result
467 )
File ~/.local/lib/python3.13/site-packages/bilibili_api/user.py:1063, in User.get_access_id(self)
1056 async def get_access_id(self) …
```

fix: 获取用户 access_id 时带上 Credential

---

bilibili_api/bangumi.py
bilibili_api/video.py

The voice_balance parameter was hardcoded to 1 in both Video and Episode classes. This change removes the default setting.

fix: Remove default voice_balance parameter to prevent it from being enabled by default
