Nemo2011/bilibili-api

bilibili_api/bangumi.py
bilibili_api/data/api/bangumi.json

语言：python
- 1. 往Episode里新增了一个get_download_url(html5: bool)方法用于获取番剧的下载地址

feat: 增加获取番剧下载地址的接口

---

bilibili_api/data/api/video.json

语言：python
- 1. 向 video.json 中部分 API 的 params 增加 bvid

docs: 更新视频 API 文件中的 bvid 参数

---

bilibili_api/data/api/user.json
bilibili_api/user.py
docs/modules/user.md

语言：python
- 1. 新增粉丝排行接口
- 2. pep8顺手修改

add top_followers api

---

docs/index.html

语言：无
- 1. 修复 bootcdn 522 timeout 错误

docs: change cdn to baomitu

---

bilibili_api/dynamic.py

1. 使用`credential.get_cookies()`作为cookie上传图片动态会返回错误码-500（未登录），迁移至`httpx`， 并使用`httpx`的`files`参数上传图片文件。
2. 一次上传多个图片时，使用`asyncio.gather`以实现协程的有效并发。

fix: 图片动态迁移至httpx (python)

---

bilibili_api/data/api/video.json
bilibili_api/video.py
docs/modules/video.md
tests/test_video.py

```
需要 cid
Returns:
dict: 调用接口返回的内容的字幕部分字段。
```
无需登陆, 获取视频播放信息Api中的字幕数据字段。
+ 增加文档
+ 增加例子
+ 增加 Api 数据
**没有对此 Api 使用内置方法进行复用**
**增加的Api为播放器Api,内含 字幕字段，地理位置，帐号权限，bgm_info 。可以扩展其他方法**
```
{
"code": 0,
"data": {
"aid": 288571926,
"allow_bp": false,
"answer_status": 0,
"bgm_info": null,
"block_time": 0,
"bvid": "BV1Gf4y1y7wc",
"cid": 281031471,
"fawkes": {
"config_version": 18088,
"ff_version": 0
},
"guide_attention": [
{
"from": 1,
"pos_x": 129,
"pos_y": 180,
"to": 6,
"type": 1
}
],
"has_next": true,
"ip_info": {
"city": "",
"country": "日本",
"ip": "28.12.16.17",
"province": "东京都",
"zone_id": 4552,
"zone_ip": " 28.12.16.17"
},
"is_owner": false,
"is_ugc_pay_preview": false,
"jump_card": [],
"last_play_cid": 0,
"last_play_time": 0,
"level_info": {
"current_exp": 0,
"current_level": 0, …
```

[Enhancement]增加 视频 播放信息 Api，增加 获取视频字幕的方法

---

bilibili_api/data/api/rank.json
bilibili_api/rank.py
docs/modules/rank.md

feat(rank): Add pagination for hot videos

feat(rank): Add pagination for hot videos

---

bilibili_api/bangumi.py

[修复 Episode 缺失 Credential](https://github.com/Nemo2011/bilibili-api/pull/114)

修复 Episode 缺失 Credential

---

bilibili_api/live.py

Fix the bug of misusing comparison as assignment

---

bilibili_api/data/api/user.json
bilibili_api/user.py
docs/modules/user.md

增加 user.edit_self_info 
我的信息 `https://space.bilibili.com/{mid}/setting`

add func user.edit_self_info

---

bilibili_api/search.py

Reverts Nemo2011/bilibili-api#110

Revert "search_by_type接口搜索10分钟以下时长视频duration值应为1"

---

bilibili_api/bangumi.py

Reverts Nemo2011/bilibili-api#115

Revert "修复 Episode 缺失 Credential"

---

bilibili_api/live.py

Reverts Nemo2011/bilibili-api#117

Revert "Fix the bug of misusing comparison as assignment"

---

bilibili_api/article.py
bilibili_api/data/api/note.json
bilibili_api/data/api/user.json
bilibili_api/data/api/video.json
bilibili_api/note.py
bilibili_api/user.py
bilibili_api/video.py
docs/modules/article.md
docs/modules/note.md
docs/modules/user.md
docs/modules/video.md

新增 Note 功能
https://github.com/Nemo2011/bilibili-api/issues/131

feat: Note

---

bilibili_api/article.py
bilibili_api/note.py
docs/examples/note.md

Fix Note bug

---

bilibili_api/utils/parse_link.py

Fix: auto_convert_video 没传 credential，以及解析视频的返回值会被嵌套两层
提问：https://github.com/Nemo2011/bilibili-api/commit/ded4a6ec1c17ab09dfa4bde5ccdd5b6f4d76df32#r97649316
```
av82054919 (<bilibili_api.video.Video object at 0x00000215E335D960>, <ResourceType.VIDEO: 'video'>)
AV82054919 (<bilibili_api.video.Video object at 0x00000215E335CC40>, <ResourceType.VIDEO: 'video'>)
BV1XJ41157tQ (<bilibili_api.video.Video object at 0x00000215E335DB10>, <ResourceType.VIDEO: 'video'>)
https://www.bilibili.com/video/av82054919 (<bilibili_api.video.Video object at 0x00000215E4397FA0>, <ResourceType.VIDEO: 'video'>)
https://www.bilibili.com/video/BV1XJ41157tQ (<bilibili_api.video.Video object at 0x00000215E43FFAC0>, <ResourceType.VIDEO: 'video'>)
https://www.bilibili.com/bangumi/media/md28237119 …
```

fix: missing credential

---

.gitignore
bilibili_api/utils/parse_link.py

uid 和 room_id 类型错误
以及补全丢失的 credential

fix typing and credential

---

bilibili_api/data/api/video_zone.json
bilibili_api/video_zone.py
docs/modules/video_zone.md
tests/test_video_zone.py

video_zone.get_zone_hot_tags

---

bilibili_api/channel.py
bilibili_api/utils/parse_link.py

use get_initial_state

---

docs/get-credential.md

勘误 get-credential.md

---

bilibili_api/data/api/rank.json
bilibili_api/rank.py
docs/modules/rank.md
tests/test_rank.py

https://manga.bilibili.com/ranking/13

feat: rank.get_manga_rank

---

bilibili_api/data/api/manga.json
bilibili_api/manga.py
bilibili_api/rank.py
docs/modules/manga.md
tests/test_manga.py

feat: manga.get_index

---

bilibili_api/tools/parser/Card.vue
bilibili_api/tools/parser/README.md
bilibili_api/tools/parser/__init__.py
bilibili_api/tools/parser/app.py
bilibili_api/tools/parser/parser.py

#184 对项目基本没作用，只是我个人的一点点小心愿，文档也不用写其实。

feat: 新增解析器

---

bilibili_api/comment.py
docs/modules/comment.md

https://api.bilibili.com/x/v2/reply?pn=1&type=22&oid=27809&sort=2

feat: manga reply

---

bilibili_api/data/api/manga.json
bilibili_api/manga.py
docs/modules/manga.md
tests/test_manga.py

更新推荐测试结果
```python
[<bilibili_api.manga.Manga object at 0x000001DD9C85EE50>, <bilibili_api.manga.Manga object at 0x000001DD9C85D310>, <bilibili_api.manga.Manga object at 0x000001DD9C857F90>, <bilibili_api.manga.Manga object at 0x000001DD9C95CFD0>, <bilibili_api.manga.Manga object at 0x000001DD9C95D090>, <bilibili_api.manga.Manga object at 0x000001DD9C95D150>]
```
首页推荐测试结果
```python
[<bilibili_api.manga.Manga object at 0x000001F8F7C84ED0>, <bilibili_api.manga.Manga object at 0x000001F8F7D72910>, <bilibili_api.manga.Manga object at 0x000001F8F7C847D0>, <bilibili_api.manga.Manga object at 0x000001F8F7D94950>, <bilibili_api.manga.Manga object at 0x000001F8F7D949D0>, <bilibili_api.manga.Manga object at 0x000001F8F7D94A90>, <bilibili_api.manga.Manga object at 0x000001F8F7D94B10>, …
```

feat: manga update and home_recommend

---

bilibili_api/creative_center.py

fix: creative_center.get_video_survey

---

bilibili_api/data/api/dynamic.json
bilibili_api/data/api/topic.json
bilibili_api/dynamic.py
bilibili_api/topic.py
docs/modules/dynamic.md
docs/modules/topic.md
tests/test_dynamic.py
tests/test_topic.py

https://github.com/Nemo2011/bilibili-api/issues/202

get_dynamic_page_info

---

bilibili_api/dynamic.py

https://github.com/Nemo2011/bilibili-api/actions/runs/4214418073/jobs/7314868087#step:5:46

fix: python3.8 support

---

bilibili_api/dynamic.py
docs/modules/dynamic.md
tests/test_dynamic.py

论没 contributors 权限和光速 merge 结合——每次都得PR

fix: dynmaic test

---

bilibili_api/dynamic.py
docs/modules/dynamic.md
tests/test_vote.py

fix emoji and vote

---

tests/test_vote.py

fix: update_vote

---

bilibili_api/data/api/rank.json
bilibili_api/rank.py
docs/modules/rank.md
tests/test_rank.py

以及 https://live.bilibili.com/p/eden/rank#/childnav/energy/0

feat: live rank

---

bilibili_api/bangumi.py
bilibili_api/channel.py
bilibili_api/utils/initial_state.py

https://github.com/Nemo2011/BiliDown/issues/2
BiliDown 是不是应该更新到 [v15.3](https://github.com/Nemo2011/bilibili-api/releases/tag/15.3.0) 了？

fix: episode credential

---

bilibili_api/black_room.py
bilibili_api/data/api/black-room.json
bilibili_api/data/api/user.json
bilibili_api/user.py
docs/modules/black_room.md
docs/modules/user.md
tests/test_black_room.py
tests/test_user.py

https://github.com/Nemo2011/bilibili-api/issues/230

feat: get_self_jury_info

---

bilibili_api/article.py
bilibili_api/game.py
tests/test_game.py

但我还是看不懂 fetch_content，没法给 opus 整个 parse...

feat: article opus

---

bilibili_api/data/api/rank.json
bilibili_api/favorite_list.py
bilibili_api/rank.py
docs/modules/favorite_list.md
docs/modules/rank.md
tests/test_rank.py

https://github.com/Nemo2011/bilibili-api/issues/260
https://github.com/Nemo2011/bilibili-api/issues/243

playlet rank and search_fav_list

---

bilibili_api/favorite_list.py
docs/modules/favorite_list.md
tests/test_favorite_list.py

feat: favorite_list.get_favorite_collected

---

bilibili_api/data/api/favorite-list.json
bilibili_api/favorite_list.py
docs/modules/favorite_list.md
tests/test_favorite_list.py

https://github.com/Nemo2011/bilibili-api/issues/273

feat: fav_list get_info & get_content_ids_info

---

bilibili_api/__init__.py
bilibili_api/utils/network_httpx.py

feat: 新增装饰器 @retry

---

CHANGELOGS/v15.md
bilibili_api/__init__.py
setup.py

release: v15.4.4

---

bilibili_api/__init__.py
bilibili_api/credential.py

fix: credential

---

bilibili_api/data/api/user.json
bilibili_api/user.py
bilibili_api/video.py
docs/modules/user.md
tests/test_user.py

- [fix: video.get_tags typing](https://github.com/Nemo2011/bilibili-api/commit/090c725996e011439b432ab777f6f8aec0cd1ce3)
- [feat: user.get_elec_user_monthly](https://github.com/Nemo2011/bilibili-api/commit/689c7a7c039c5bb2475d99c4a9f17c5fa9eca804)

fix typing and feat user module

---

bilibili_api/credential.py
bilibili_api/video.py

fix: 修复Video.get_pages hint #350 
fix: 修复credential刷新函数没有异步 #351

fix: 修复credential刷新函数没有异步

---

bilibili_api/data/api/user.json
bilibili_api/user.py
docs/modules/user.md
tests/test_user.py

feat: user.get_self_history_new

---

CHANGELOGS/v15.md

changelog: 15.5.1

---

bilibili_api/live.py
bilibili_api/utils/network_httpx.py

fix: 修复 params 中有汉字时计算 w_rid 错误的漏洞以及弹幕用户名打码问题

---

bilibili_api/data/api/user.json
bilibili_api/user.py
docs/modules/user.md

https://github.com/SocialSisterYi/bilibili-API-collect/blob/436f26f15bab7855184e40b21c54ab0e41fb6133/docs/user/relation.md#%E6%9F%A5%E8%AF%A2%E7%94%A8%E6%88%B7%E5%85%B3%E6%B3%A8%E6%98%8E%E7%BB%86
顺便修下
```diff
-       self.__self_info = await get_self_info(credential=self.credential)
+       self.__self_info = await self.get_user_info()
```

fix: update get_followings

---

bilibili_api/data/api/login.json
bilibili_api/login.py
bilibili_api/login_func.py
docs/examples/login.md
docs/modules/login.md
requirements.txt

在 https://github.com/Nemo2011/bilibili-api/pull/369 的基础上重构了下

rechore: login term and tk

---

bilibili_api/__init__.py
setup.py

release: 15.5.1.b0

---

bilibili_api/comment.py
bilibili_api/utils/network_httpx.py

https://github.com/Nemo2011/bilibili-api/issues/390

fix: buvid3

---

bilibili_api/data/api/rank.json
bilibili_api/rank.py

https://github.com/Nemo2011/bilibili-api/actions/runs/5655463836/job/15320635861

fix: shit fix

---

bilibili_api/data/api/user.json
bilibili_api/user.py

- 1. {新增}
- 2. {修复}
- 3. {其他}
删除 `need_top` 接口不再支持此参数

fix: [BREADKING CHANGE] update user.get_dynamics

---

CHANGELOGS/v15.md
bilibili_api/__init__.py
bilibili_api/bangumi.py
bilibili_api/utils/initial_state.py
setup.py

fix: ep meta info

---

bilibili_api/bangumi.py
bilibili_api/data/api/user.json
bilibili_api/user.py
bilibili_api/utils/initial_state.py
index.html

fix: host_mid

---

bilibili_api/data/api/session.json
bilibili_api/session.py

https://github.com/Nemo2011/bilibili-api/issues/442

feat: session.get_at

---

bilibili_api/data/api/credential.json
bilibili_api/login.py
bilibili_api/utils/credential.py
bilibili_api/utils/network_httpx.py

feat: video.Video.share

---

bilibili_api/session.py
bilibili_api/utils/picture.py

https://github.com/Nemo2011/bilibili-api/pull/367#issuecomment-1698692891
```python
from bilibili_api import Credential, Picture, session, sync
cred = Credential(
sessdata="",
bili_jct="",
buvid3="",
)
async def main():
pic = Picture.from_file("C:/.../xxx.jpg")
await session.send_msg(cred, 2, session.Event.PICTURE, pic)  # Succeed
await session.send_msg(cred, 2, session.Event.PICTURE, "test")  # TypeError
sync(main())
```

fix: 图片一段时间后消失

---

requirements.txt
tests/test_root_functions.py

具体其他操作文档再说吧...没空了
- 1. {新增}
- 2. {修复}
- 3. {其他}

fix: test album url

---

bilibili_api/data/api/user.json
bilibili_api/user.py

feat: user.get_uplikeimg

---

bilibili_api/watchroom.py

fix: watchroom

---

bilibili_api/utils/network.py

有的接口不一定要 verify，建议得开个新值 must_verify

fix: if self.verify

---

bilibili_api/utils/network.py

'AsyncClient' object has no attribute 'ws_connect'

fix: session_pool

---

tests/test_article.py
tests/test_topic.py

test: 65006 34005

---

CHANGELOGS/v16.md
bilibili_api/__init__.py
setup.py

release: v16.0.0

---

bilibili_api/data/api/credential.json
bilibili_api/data/api/user.json
bilibili_api/video.py
tests/test_video.py

fix: 4165be

---

bilibili_api/live.py
bilibili_api/utils/network.py

https://github.com/Nemo2011/bilibili-api/issues/479
非常不情愿的把 credential 设置为必填项，之前用房主 uid 骗弹幕的方案也失效了

修复弹幕读取和 httpx.AsyncClient 关闭错误问题

---

CHANGELOGS/v16.md
bilibili_api/live.py

fix: 通过 sessdata 获取 dedeuserid

---

bilibili_api/data/api/live.json
bilibili_api/live.py

fix: 更换直播弹幕获取接口后强制凭证需要提供 sessdata 和 buvid3

---

bilibili_api/data/api/dynamic.json
bilibili_api/dynamic.py
docs/modules/dynamic.md

490 漏洞 dynamic模块url固定无法改参

---

bilibili_api/data/api/show.json
bilibili_api/show.py
bilibili_api/utils/network.py
bilibili_api/utils/utils.py
docs/modules/show.md
tests/test_show.py
tests/test_video.py

feat: 增加会员购会展相关接口

---

bilibili_api/data/api/video_uploader.json
bilibili_api/video_uploader.py

fix: video_uploader submit api v3

---

bilibili_api/creative_center.py
bilibili_api/data/api/creative_center.json
docs/modules/creative_center.md
tests/test_creative_center.py

https://github.com/Nemo2011/bilibili-api/issues/518

扩充创作中心相关接口

---

bilibili_api/comment.py
bilibili_api/data/api/user.json
bilibili_api/user.py
docs/modules/user.md
tests/test_user.py

- 1. {新增}
- 2. {修复}
- 3. {其他}
顺便修了下 `sort` 参数见修改

feat: user.get_relation

---

bilibili_api/data/api/user.json
bilibili_api/user.py
docs/modules/user.md
tests/test_user.py

feat: user.get_masterpiece

---

bilibili_api/comment.py
bilibili_api/data/api/common.json
bilibili_api/user.py
docs/modules/comment.md
tests/test_comment.py

- 1. {新增}
- 2. {修复}
- 3. {其他}
https://github.com/Nemo2011/bilibili-api/issues/530

feat: comment.report

---

bilibili_api/comment.py

Accidentally marked as comment

---

CHANGELOGS/v16.md
bilibili_api/__init__.py

release: v16.1.1

---

CHANGELOGS/v16.md

changelog: add feat

---

bilibili_api/data/api/bangumi.json

https://github.com/Nemo2011/bilibili-api/issues/546

fix: POST params -400

---

bilibili_api/data/api/video_uploader.json
bilibili_api/utils/network.py
bilibili_api/video_uploader.py
docs/examples/video_uploader.md
docs/modules/video_uploader.md

video_uploader enhancement

---

bilibili_api/credential.py
bilibili_api/utils/network.py

412 Precondition Failed 缺少 headers
- 1. {新增}
- 2. {修复}
- 3. {其他}

fix: credential.refresh

---

bilibili_api/data/api/live.json
bilibili_api/live.py
docs/modules/live.md

https://github.com/Nemo2011/bilibili-api/issues/550

feat: live.send_danmaku.reply_mid

---

bilibili_api/data/api/live.json
bilibili_api/live.py
docs/modules/live.md
tests/test_live.py

- 1. {新增} 
- bilibili_api/live.py Class LiveRoom
- get_popular_ticket_num(self) -> dict
- popular_rank_free_score_incr(self) -> dict
- bilibili_api/data/api/live.json
-  "popular_ticket"
-  "send_popular_ticket"
- tests/test_live.py
- test_zf_get_get_popular_ticket_num()
- test_zg_popular_rank_free_score_incr()
测试见 https://colab.research.google.com/drive/1G1FP3TstJUx3nKz1NvIqYDHnBW50nty5?usp=sharing

增加查看及赠送免费人气票功能

---

bilibili_api/live.py

看到目前`get_black_list()`是把页数`ps=1`写死了。把它改为一个参数即可翻页，默认值为1.
本来就有这个参数，只是改为可调，就不修改API，文档，和test了
测试见：https://colab.research.google.com/drive/1G1FP3TstJUx3nKz1NvIqYDHnBW50nty5?usp=sharing

get_black_list 增加翻页功能

---

bilibili_api/data/api/live.json
bilibili_api/live.py
docs/modules/live.md

- 修复 unban_user 更换了新的 api 接口。
[测试成功](https://colab.research.google.com/drive/1IVvuwtkoTujJ9NcP8Z_i1ge7yFgWsLZf?usp=sharing)

fix unban_user

---

bilibili_api/credential.py
bilibili_api/utils/captcha.py

- 1. {新增}
- 2. {修复} 修复刷新cookie和使用验证码登录时发生的异常
- 3. {其他}

fix: 修复刷新cookie和使用验证码登录时发生的异常

---

bilibili_api/data/api/user.json
bilibili_api/user.py

https://github.com/Nemo2011/bilibili-api/issues/595
- 1. {新增}
- 2. {修复}
- 3. {其他}

fix: -352 风控

---

bilibili_api/channel_series.py
bilibili_api/video_uploader.py

fix: returns 412 msg for channel series by adding ua

---

bilibili_api/video_uploader.py

fix: problems from git hook in video_uploader.py

---

bilibili_api/utils/network.py

修 https://github.com/Nemo2011/bilibili-api/pull/615 剩下的

feat: sync cache result

---

bilibili_api/session.py
docs/modules/session.md

feat: EventType

---

bilibili_api/utils/network.py

- 1. {新增}
- 2. {修复}
- 3. {其他}
https://github.com/SocialSisterYi/bilibili-API-collect/issues/903

feat: bili_ticket

---

bilibili_api/data/api/login.json
bilibili_api/login.py
bilibili_api/search.py
docs/modules/search.md

参考 https://github.com/XiaoMiku01/fansMedalHelper/blob/master/logintool/login.go
只确定可以用 `user.get_self_info`，不清楚 tv 的 cookie 到底能不能用，需要测试...我这实在没空
以及 APP 签名的鉴权也许可以安排下，画个大饼

feat: login with tv

---

bilibili_api/live.py

- 1. {新增}
- 2. {修复} 重连清理无效的ws链接和心跳任务，略微提高弹幕链接稳定性
- 3. {其他}

fix: live.py重连清理无效的ws链接和心跳任务，略微提高弹幕链接稳定性

---

bilibili_api/comment.py
bilibili_api/data/api/common.json
bilibili_api/video_uploader.py

https://github.com/SocialSisterYi/bilibili-API-collect/blob/e6f1e7829d3eebb5011f4d6a1e798e9db7e135ef/docs/comment/list.md#%E8%8E%B7%E5%8F%96%E8%AF%84%E8%AE%BA%E5%8C%BA%E6%98%8E%E7%BB%86_%E6%87%92%E5%8A%A0%E8%BD%BD
- 1. {新增}
- 2. {修复}
- 3. {其他}

fix: get_comment_lazy

---

bilibili_api/__init__.py

`__init__.py`忘改了。
然后麻烦Pypi也发下最新版，感谢大佬们！

chore: bump version to 16.2.0

---

bilibili_api/utils/credential.py
bilibili_api/utils/credential_refresh.py

**NOTICE**: Only for async now, complete needed.
- 1. {新增}
- 2. {修复}
- 3. {其他}
https://github.com/Nemo2011/bilibili-api/issues/692

feat: 自定义 Credential Cookies

---

README.md
bilibili_api/login_func.py
docs/README.md

修复 因 login.login_with_key 返回的值没有 data 字段引起的 bug

修复 因 login.login_with_key 返回的值没有 data 字段引起的 bug

---

bilibili_api/video.py

Avoid shadowing lan parameter in subtitle posting

---

bilibili_api/video_uploader.py

This solves #698
之前有 typo，修改还是不能用

Fix typo in video_uploader.py

---

bilibili_api/video_uploader.py

Pass source in meta to dict for upload

---

bilibili_api/video_uploader.py

Removed duplicated _choose_line and _probe function
Handled timeout during upload probing (fixes #711)
Uses `json_body` for video update API (similar to #507)

Fix timeout and other issues in video_uploader

---

bilibili_api/data/api/live.json
bilibili_api/live.py

- 1.修复start stop 接口bug， verify=true, 本地测试验证成功。

debug: start/stop live with verify

---

bilibili_api/data/api/video.json
bilibili_api/video.py

fix: enable WBI sign for playurl

---

bilibili_api/data/api/search.json
bilibili_api/search.py

fix: apply WBI sign to search-* apis

---

bilibili_api/data/api/live.json
bilibili_api/live.py

- 1. {新增}
- 2. {修复} 直播开启、关闭的bug修复
- 3. {其他} 发送弹幕允许增加room_id参数，减少内部调用接口

debug startLive; send_damaku performance(without get roomid)

---

bilibili_api/utils/network.py

修复CHUNK_FAILED的问题
- 1. {修复}设置httpx的超时时间，通过settings.timeout的设置

HTTPX timeout设置使用settings.timeout

---

bilibili_api/data/api/live.json
bilibili_api/live.py
docs/modules/live.md
tests/test_live.py

新增获取直播间可用表情包，直播间发送表情包功能
测试： https://colab.research.google.com/drive/1zR8Rm8BPiyamOpFI2se8SUMccwvqEuzO?usp=sharing
解决了#819 
与 #766 相同。还是获取不到充电表情，不过这样已经足够好了。

新增获取直播间可用表情包，与直播间发送表情包功能

---

pyproject.toml

此 Pull Request 包含以下更改：
- 修復了 `pyproject.toml` 中的配置問題，解決了靜態和動態依賴定義衝突。
- 優化了依賴管理，確保符合 PEP 621 規範。
1. **移除 `project.dynamic` 中的 `dependencies` 定義**：
- 避免與靜態定義的 `dependencies` 衝突。
2. **更新 `pyproject.toml` 文件**：
- 確保依賴項從 `requirements.txt` 正確解析。
如果有相關的 Issue，請在此處鏈接：
- Fixes #919

Fixes #919 PEP 621影響uv add安裝軟件包

---

bilibili_api/data/api/live.json
bilibili_api/live.py

直播 开关播需鉴权， 本地已验证
- 2. {修复}
使用已有函数， _enc_sign

live start/stop need sign

---

bilibili_api/comment.py
bilibili_api/data/api/common.json
bilibili_api/data/api/dynamic.json
bilibili_api/data/api/emoji.json
bilibili_api/dynamic.py
bilibili_api/emoji.py
bilibili_api/utils/network.py
bilibili_api/utils/picture.py

[feat(utils): 为 Picture 类添加 to_json 方法]
[feat(utils): 添加不同账号的代理支持并优化请求客户端]
1. 可以在不同Credential设定不同的代理
2. 对不同请求地址添加不同的timeout，让其可以自定义（对upload_image来说上传图片过大会导致timeout）
[feat(emoji): 添加表情包功能]
[feat(dynamic): 优化 @ 提及功能并添加网页转发支持]
[feat(comment): 添加发送评论时附加图片功能]

添加带图评论 优化Credential和请求代理与timeout|添加表情包功能|添加网页转发支持|添加发送评论时附加图片功能

---

bilibili_api/live.py

修复 [#issue965](https://github.com/Nemo2011/bilibili-api/issues/965)中提到的bug

fix: issue#965
